[package]
name = "echo-server"
version = "0.6.0"
edition = "2021"
authors = [
    "Harry Bairstow <harry@walletconnect.com>"
]
build = "build.rs"

[features]
default = []
tenant_write = []

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6", features = ["json"] }
tower = "0.4"
tower-http = { version = "0.3", features = ["trace"] }
hyper = "0.14"

# Database
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "json", "chrono", "macros"] }

# Seralisation
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Env Vars
dotenv = "0.15"
envy = "0.4"

# Build-time info
build-info = "0.0"

# Tracing and Telemetry
opentelemetry = { version = "0.17", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.10", features = ["metrics", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-opentelemetry = "0.17"

# Push
a2 = { git = "https://github.com/walletconnect/a2.git", branch = "v0.7" }
fcm = "0.9"

# Signature validation
ed25519-dalek = "1.0"

# Misc
reqwest = "0.11"
async-trait = "0.1"
thiserror = "1.0"
hex = "0.4"
base64 = "0.13"
chrono = "0.4"

[dev-dependencies]
serial_test = "0.9"
test-context = "0.1"
futures-util = "0.3"

[build-dependencies]
build-info-build = "0.0"
