[package]
name = "echo-server"
version = "0.1.0"
edition = "2021"
authors = [
    "Harry Bairstow <harry@walletconnect.com>"
]
build = "build.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6.0-rc.2", features = ["json"] }
hyper = "0.14.20"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["map-request-body", "util"] }

# Database
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "json", "macros"] }

# Seralisation
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Env Vars
dotenv = "0.15.0"
envy = "0.4"

# Build-time info
build-info = "0.0.27"

# Tracing and Telemetry
opentelemetry = { version = "0.17.0", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.10.0", features = ["metrics", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3.15"
tracing-opentelemetry = "0.17.4"

# Push
a2 = { git = "https://github.com/walletconnect/a2.git", branch = "v0.7" }
fcm = "0.9.2"

# Signature validation
ed25519-dalek = "1.0.1"

# Misc
reqwest = "0.11.12"
async-trait = "0.1.57"
thiserror = "1.0.36"
hex = "0.4.3"
chrono = "0.4.22"

[dev-dependencies]
serial_test = "0.9.0"

[build-dependencies]
build-info-build = "0.0.27"
