[package]
name = "echo-server"
version = "0.1.0"
edition = "2021"
authors = [
    "Harry Bairstow <harry@walletconnect.com>"
]
build = "build.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6.0-rc.2", features = ["json"] }

sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "postgres", "json", "macros"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

dotenv = "0.15.0"
envy = "0.4"

build-info = "0.0.27"

opentelemetry = { version = "0.17.0", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.10.0", features = ["metrics", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3.15"
tracing-opentelemetry = "0.17.4"

a2 = { git = "https://github.com/walletconnect/a2.git", branch = "v0.7" }
fcm = "0.9.2"

async-trait = "0.1.57"
thiserror = "1.0.36"

[dev-dependencies]
serial_test = "0.9.0"

[build-dependencies]
build-info-build = "0.0.27"
