version: '3.9'
services:
  postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=root

  echo-server:
      build: .
      depends_on:
        - jaeger
        - postgres
      ports:
        - "3000:3000"
        - "3002:3002"
      environment:
        - PORT=3000
        - LOG_LEVEL=info,echo-server=info
        - DATABASE_URL=postgres://postgres:root@postgres:5432/postgres
        - TELEMETRY_PROMETHEUS_PORT=3002
