name: auto_deploy

on:
  push:
    branches:
      - main

jobs:
  build-container:
    runs-on:
      group: ubuntu-runners
    strategy:
      matrix:
        file: [Dockerfile, slim.Dockerfile]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Authenticate with ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Set tag suffix
        id: suffix
        run: |
          if [[ "${{ matrix.file }}" == *.* ]]; then
            echo "::set-output name=suffix:::$(echo "${{ matrix.file }}" | cut -d'.' -f1)"
          else
            echo "::set-output name=suffix::"
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/echo-server
            ghcr.io/${{ github.repository }}
            walletconnect/echo-server,enable=false
          flavor: |
            latest=auto
          tags: |
            type=raw,value=${{ github.ref_name }},suffix=${{ steps.suffix.outputs.suffix }}

      # Setup Buildkit
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, tag, and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  run-ci:
    uses: ./.github/workflows/ci.yml
  run-cd:
    needs:
      - build-container
      - run-ci
    # call the cd.yml file with image tag as the commit hash
    uses: ./.github/workflows/cd.yml
    with:
      image_tag: ${{ github.ref_name }}
